import { motion, useScroll, useTransform } from 'motion/react';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, X } from 'lucide-react';
import { RevealOnScroll, SectionLabel } from '../components/AnimatedElements';
import { galleryImages } from '../data/galleryImages';

/* galleryImages is auto-generated by scripts/gen-thumbs.mjs (`npm run thumbs`).
   Full-res originals live in /public/gallery/<id>.webp; the grid uses the
   compressed copies in /public/gallery/thumbs (the lightbox uses full-res). */
const thumbSrc = (id) => `/gallery/thumbs/${id}.webp`;
const fullSrc = (id) => `/gallery/${id}.webp`;

/* How many photos to load per batch (infinite scroll) */
const BATCH = 20;

/*
 * Layout by breakpoint:
 *  - Tablet & desktop ("brick"): rows cycle through counts (e.g. 4 then 3) and each
 *    row fills the full width, so a 3-row's tiles are wider than a 4-row's — the seam
 *    mismatch gives the brick-wall offset. The final leftover row keeps the base
 *    (1 / maxCols) tile size instead of stretching.
 *  - Mobile ("grid"): a clean uniform 2-column grid.
 */
function getLayout(w) {
  if (w >= 1024) return { mode: 'brick', pattern: [4, 3], gap: 16 };
  if (w >= 768) return { mode: 'brick', pattern: [3, 2], gap: 16 };
  return { mode: 'grid', cols: 2, gap: 12 };
}

function useLayout() {
  const [layout, setLayout] = useState(() =>
    typeof window === 'undefined' ? { mode: 'brick', pattern: [4, 3], gap: 16 } : getLayout(window.innerWidth)
  );
  useEffect(() => {
    const onResize = () => setLayout(getLayout(window.innerWidth));
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);
  return layout;
}

/* Chunk the (currently visible) images into rows following the pattern */
function buildRows(images, pattern) {
  const rows = [];
  let i = 0;
  let r = 0;
  while (i < images.length) {
    const count = pattern[r % pattern.length];
    const row = [];
    for (let c = 0; c < count && i < images.length; c++) {
      row.push({ id: images[i], index: i });
      i++;
    }
    rows.push(row);
    r++;
  }
  return rows;
}

export default function Gallery() {
  const [lightboxIndex, setLightboxIndex] = useState(null);
  const [visibleCount, setVisibleCount] = useState(BATCH);
  const [loaded, setLoaded] = useState({});
  const isOpen = lightboxIndex !== null;

  const layout = useLayout();
  const isGrid = layout.mode === 'grid';
  const visibleImages = galleryImages.slice(0, visibleCount);
  const rows = isGrid ? [] : buildRows(visibleImages, layout.pattern);
  const hasMore = visibleCount < galleryImages.length;

  const sentinelRef = useRef(null);

  const heroRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: heroRef,
    offset: ["start start", "end start"],
  });
  const heroY = useTransform(scrollYProgress, [0, 1], [0, 150]);
  const heroOpacity = useTransform(scrollYProgress, [0, 0.6], [1, 0]);

  const markLoaded = (id) => setLoaded((prev) => (prev[id] ? prev : { ...prev, [id]: true }));

  const openLightbox = (idx) => setLightboxIndex(idx);
  const closeLightbox = () => setLightboxIndex(null);
  const showPrev = () =>
    setLightboxIndex((i) => (i - 1 + galleryImages.length) % galleryImages.length);
  const showNext = () =>
    setLightboxIndex((i) => (i + 1) % galleryImages.length);

  /* Infinite scroll — load the next batch when the sentinel nears the viewport */
  useEffect(() => {
    if (!hasMore) return;
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          setVisibleCount((c) => Math.min(c + BATCH, galleryImages.length));
        }
      },
      { rootMargin: '600px 0px' } // preload before the user reaches the bottom
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [hasMore, visibleCount]);

  useEffect(() => {
    document.body.style.overflow = isOpen ? 'hidden' : '';
    return () => { document.body.style.overflow = ''; };
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;
    const onKey = (e) => {
      if (e.key === 'Escape') closeLightbox();
      if (e.key === 'ArrowLeft') showPrev();
      if (e.key === 'ArrowRight') showNext();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [isOpen]);

  // Base tile width (brick mode) — used to keep the final partial row tidy.
  const maxCols = isGrid ? layout.cols : layout.pattern[0];
  const baseWidth = `calc((100% - ${(maxCols - 1) * layout.gap}px) / ${maxCols})`;

  // Skeleton + image, shared by both layouts (wrapper supplies size/shape).
  const renderTile = (id, index) => {
    const isLoaded = loaded[id];
    return (
      <>
        <div
          className={`absolute inset-0 bg-warm-100 animate-pulse transition-opacity duration-500 ${
            isLoaded ? 'opacity-0' : 'opacity-100'
          }`}
        />
        <img
          src={thumbSrc(id)}
          alt={`Welcome Homes WA gallery ${index + 1}`}
          loading="lazy"
          decoding="async"
          onLoad={() => markLoaded(id)}
          className={`relative w-full h-full object-cover transition duration-500 group-hover:scale-105 ${
            isLoaded ? 'opacity-100' : 'opacity-0'
          }`}
        />
      </>
    );
  };

  return (
    <>
      {/* ===== HERO ===== */}
      <section ref={heroRef} className="relative h-[55vh] sm:h-[65vh] lg:h-[75vh] min-h-87.5 sm:min-h-125 overflow-hidden">
        <motion.div style={{ y: heroY }} className="absolute inset-0">
          <img
            src={fullSrc("17")}
            alt="Welcome Homes WA gallery"
            className="w-full h-full object-cover"
            loading="eager"
            fetchPriority="high"
          />
          <div className="absolute inset-0 bg-linear-to-b from-black/50 via-black/30 to-black/60" />
        </motion.div>

        <motion.div
          style={{ opacity: heroOpacity }}
          className="relative z-10 h-full flex flex-col justify-end pb-16 sm:pb-20 lg:pb-28 px-5 sm:px-8 lg:px-12 max-w-350 mx-auto"
        >
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.8 }}
            className="text-white text-xs sm:text-sm tracking-[0.25em] uppercase mb-4"
          >
            Our Gallery
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 1, ease: [0.16, 1, 0.3, 1] }}
            className="hero-heading text-4xl sm:text-5xl lg:text-6xl text-white leading-[1.1] max-w-3xl"
          >
            A look inside<br />
            our <span className="italic">homes</span>
          </motion.h1>
        </motion.div>
      </section>

      {/* ===== BRICK WALL GRID ===== */}
      <section className="section-padding bg-linear-to-b from-white to-warm-50">
        <div className="max-w-350 mx-auto px-5 sm:px-8 lg:px-12">
          <RevealOnScroll>
            <div className="mb-10 sm:mb-14 max-w-2xl">
              <SectionLabel>Gallery</SectionLabel>
              <p className="text-charcoal-500 text-base sm:text-lg leading-relaxed">
                A collection of moments from the homes we've designed and built across
                Perth — the craftsmanship, the spaces, and the details that make each one unique.
              </p>
            </div>
          </RevealOnScroll>

          {isGrid ? (
            /* Mobile — clean uniform 2-column grid */
            <div className="grid grid-cols-2 gap-3">
              {visibleImages.map((id, i) => (
                <div
                  key={id}
                  onClick={() => openLightbox(i)}
                  className="group relative aspect-4/3 overflow-hidden rounded-xl cursor-pointer bg-warm-100 shadow-sm"
                >
                  {renderTile(id, i)}
                </div>
              ))}
            </div>
          ) : (
            /* Tablet & desktop — full-width brick rows (alternating 4 / 3) */
            <div className="space-y-3 sm:space-y-4">
              {rows.map((row, ri) => {
                const intended = layout.pattern[ri % layout.pattern.length];
                // Once everything is loaded, don't stretch a leftover final row.
                const isPartial = !hasMore && ri === rows.length - 1 && row.length < intended;
                return (
                  <div key={ri} className="flex" style={{ gap: `${layout.gap}px` }}>
                    {row.map((brick) => (
                      <div
                        key={brick.id}
                        onClick={() => openLightbox(brick.index)}
                        style={isPartial ? { width: baseWidth } : undefined}
                        className={`group relative ${isPartial ? 'flex-none' : 'flex-1'} min-w-0 h-36 sm:h-48 lg:h-56 overflow-hidden rounded-xl cursor-pointer bg-warm-100 shadow-sm hover:shadow-md transition-shadow duration-300`}
                      >
                        {renderTile(brick.id, brick.index)}
                      </div>
                    ))}
                  </div>
                );
              })}
            </div>
          )}

          {/* Infinite-scroll sentinel + loading hint */}
          {hasMore && (
            <div ref={sentinelRef} className="flex justify-center py-10">
              <div className="flex items-center gap-2 text-charcoal-400 text-sm">
                <span className="w-4 h-4 rounded-full border-2 border-charcoal-300 border-t-transparent animate-spin" />
                Loading more
              </div>
            </div>
          )}
        </div>
      </section>

      {/* ===== LIGHTBOX ===== */}
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="fixed inset-0 z-9999 bg-black/95 flex items-center justify-center p-4"
          onClick={closeLightbox}
        >
          <button
            onClick={closeLightbox}
            className="absolute top-5 right-5 z-10 p-2 rounded-full bg-black/30 text-white/70 hover:text-white hover:bg-black/50 transition-colors"
            aria-label="Close"
          >
            <X size={22} />
          </button>

          <button
            onClick={(e) => { e.stopPropagation(); showPrev(); }}
            className="absolute left-3 sm:left-6 top-1/2 -translate-y-1/2 z-10 p-2 rounded-full bg-black/30 text-white/70 hover:text-white hover:bg-black/50 transition-colors"
            aria-label="Previous image"
          >
            <ArrowLeft size={22} />
          </button>

          <motion.img
            key={lightboxIndex}
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.3 }}
            src={fullSrc(galleryImages[lightboxIndex])}
            alt={`Welcome Homes WA gallery ${lightboxIndex + 1}`}
            onClick={(e) => e.stopPropagation()}
            className="max-w-full max-h-[85vh] object-contain rounded-lg select-none"
          />

          <button
            onClick={(e) => { e.stopPropagation(); showNext(); }}
            className="absolute right-3 sm:right-6 top-1/2 -translate-y-1/2 z-10 p-2 rounded-full bg-black/30 text-white/70 hover:text-white hover:bg-black/50 transition-colors"
            aria-label="Next image"
          >
            <ArrowRight size={22} />
          </button>

          <div className="absolute bottom-5 left-1/2 -translate-x-1/2 text-white/60 text-sm tracking-wide">
            {lightboxIndex + 1} / {galleryImages.length}
          </div>
        </motion.div>
      )}
    </>
  );
}
