// Generate compressed gallery thumbnails for the grid AND the image list the page uses.
// Originals stay untouched in public/gallery; the lightbox uses those.
// Usage: npm run thumbs  (run after adding/removing images in public/gallery)
import sharp from 'sharp';
import { readdirSync, mkdirSync, existsSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, '..', 'public', 'gallery');
const outDir = join(srcDir, 'thumbs');
const listFile = join(__dirname, '..', 'src', 'data', 'galleryImages.js');

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

const files = readdirSync(srcDir).filter((f) => /\.webp$/i.test(f));

// Generate thumbnails
console.log(`Generating ${files.length} thumbnails -> ${outDir}`);
let done = 0;
for (const file of files) {
  await sharp(join(srcDir, file))
    .resize({ width: 800, withoutEnlargement: true })
    .webp({ quality: 72 })
    .toFile(join(outDir, file));
  done += 1;
  process.stdout.write(`\r(${done}/${files.length}) ${file}            `);
}

// Write the (numerically sorted) image list the gallery imports
const stems = files
  .map((f) => f.replace(/\.webp$/i, ''))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const contents =
  `// AUTO-GENERATED by scripts/gen-thumbs.mjs — do not edit by hand.\n` +
  `// Run \`npm run thumbs\` after adding/removing images in public/gallery.\n` +
  `export const galleryImages = ${JSON.stringify(stems, null, 2)};\n`;

writeFileSync(listFile, contents);

console.log(`\nDone. Wrote ${stems.length} entries -> ${listFile}`);
